import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { createFlow, getFlow, getMedia, updateFlow, uploadMedia } from "../services/flowService.js";
import { getTemplates } from "../services/templateService.js";
import { getOrganizationMembers } from "../../shared/services/organizationService.js";

const types = [["send_text","Send text message"],["send_template","Send approved template"],["send_media","Send image/document/media"],["ask_question","Ask question"],["wait_reply","Wait for customer reply"],["options","Button/list options"],["branch","Condition / branch"],["add_tag","Add tag"],["remove_tag","Remove tag"],["create_deal","Create deal"],["update_deal","Update deal"],["assign_member","Assign team member"],["notify_team","Notify team"],["delay","Delay / wait"],["end","End flow"]];
const emptyStep = () => ({ type: "send_text", text: "" });

function FlowBuilder() {
  const { flowId } = useParams(); const navigate = useNavigate();
  const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [status,setStatus]=useState("draft");
  const [trigger,setTrigger]=useState({type:"message_contains",value:""}); const [steps,setSteps]=useState([emptyStep()]);
  const [templates,setTemplates]=useState([]); const [members,setMembers]=useState([]); const [media,setMedia]=useState([]); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(() => { Promise.all([getTemplates({status:"approved"}),getOrganizationMembers(),getMedia(),flowId?getFlow(flowId):Promise.resolve(null)]).then(([t,m,a,f])=>{setTemplates(t);setMembers(m.filter(x=>x.status==="active"));setMedia(a);if(f){setName(f.name);setDescription(f.description);setStatus(f.status);setTrigger(f.start_trigger_json);setSteps(f.steps_json.length?f.steps_json:[emptyStep()]);}}).catch(()=>setError("Unable to load flow builder options.")); },[flowId]);
  async function handleMediaUpload(i,file){if(!file)return;setError("");try{const item=await uploadMedia(file);setMedia(await getMedia());setSteps(items=>items.map((s,n)=>n===i?{...s,media_type:item.media_type,media_id:item.id,filename:item.original_filename}:s));}catch(e){setError(e.response?.data?.detail||"Unable to upload media.");}}
  function updateStep(i,field,value){setSteps(items=>items.map((s,n)=>n===i?(field==="type"?{type:value}:{...s,[field]:value}):s));}
  function move(i,d){setSteps(items=>{const n=[...items],t=i+d;if(t<0||t>=n.length)return items;[n[i],n[t]]=[n[t],n[i]];return n;});}
  async function save(nextStatus){setSaving(true);setError("");try{const payload={name,description,status:nextStatus,start_trigger_json:trigger,steps_json:steps};if(flowId)await updateFlow(flowId,payload);else await createFlow(payload);navigate("/flows");}catch(e){setError(e.response?.data?.steps_json?.[0]||e.response?.data?.name?.[0]||"Unable to save flow.");}finally{setSaving(false);}}
  return <section className="builder-page"><header className="builder-topbar"><Link className="button" to="/flows">Back</Link><div className="builder-title-group"><label className="builder-name-label">Flow name<input className="builder-title-input" onChange={e=>setName(e.target.value)} placeholder="Name this customer journey" value={name}/></label></div><button className="button" disabled={saving} onClick={()=>save("draft")}>Save Draft</button><button className="button button--primary" disabled={saving} onClick={()=>save("active")}>Save & Activate</button></header>
    <div className="builder-canvas automation-builder-canvas"><article className="builder-node automation-builder-node"><span>Flow details</span><label>Description<textarea rows="2" value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">Draft</option><option value="active">Active</option></select></label></article>
    <article className="builder-node automation-builder-node"><span>Start trigger</span><label>Trigger<select value={trigger.type} onChange={e=>setTrigger({...trigger,type:e.target.value})}><option value="message_contains">Inbound message contains</option><option value="message_equals">Inbound message equals</option></select></label><input placeholder="For example: Hi" value={trigger.value||""} onChange={e=>setTrigger({...trigger,value:e.target.value})}/></article>
    <article className="builder-node automation-builder-node"><span>Conversation journey</span>{steps.map((step,i)=><div className="automation-action-editor" key={i}><div className="automation-builder-row"><strong>{i+1}</strong><select value={step.type} onChange={e=>updateStep(i,"type",e.target.value)}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="button button--small" disabled={!i} onClick={()=>move(i,-1)}>Up</button><button className="button button--small" disabled={i===steps.length-1} onClick={()=>move(i,1)}>Down</button><button className="button button--small" onClick={()=>setSteps(x=>x.filter((_,n)=>n!==i))}>Remove</button></div>
      {["send_text","ask_question","options"].includes(step.type)?<textarea rows="3" placeholder={step.type==="options"?"Please choose:\n1. Pricing\n2. Demo\n3. Support":"Message text"} value={step.text||""} onChange={e=>updateStep(i,"text",e.target.value)}/>:null}
      {step.type==="send_template"?<select value={step.template_id||""} onChange={e=>updateStep(i,"template_id",Number(e.target.value))}><option value="">Select approved template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} ({t.language})</option>)}</select>:null}
      {step.type==="send_media"?<div className="automation-media-action"><select value={step.media_type||"image"} onChange={e=>updateStep(i,"media_type",e.target.value)}><option value="image">Image</option><option value="document">Document</option><option value="video">Video</option><option value="audio">Audio</option></select><label className="button button--small">Upload Media<input hidden type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.mp4,.mp3,.wav" onChange={e=>{handleMediaUpload(i,e.target.files?.[0]);e.target.value="";}}/></label><select value={step.media_id||""} onChange={e=>{const a=media.find(x=>String(x.id)===e.target.value);setSteps(items=>items.map((s,n)=>n===i?{...s,media_id:a?.id||"",filename:a?.original_filename||""}:s));}}><option value="">Select media</option>{media.filter(a=>a.media_type===(step.media_type||"image")).map(a=><option key={a.id} value={a.id}>{a.original_filename}</option>)}</select><textarea placeholder="Optional caption" value={step.caption||""} onChange={e=>updateStep(i,"caption",e.target.value)}/></div>:null}
      {["add_tag","remove_tag"].includes(step.type)?<input placeholder="Tag name" value={step.tag_name||""} onChange={e=>updateStep(i,"tag_name",e.target.value)}/>:null}
      {["create_deal","update_deal"].includes(step.type)?<select value={step.stage||"New"} onChange={e=>updateStep(i,"stage",e.target.value)}><option>New</option><option>Qualified</option><option>Proposal</option><option>Won</option></select>:null}
      {step.type==="assign_member"?<select value={step.agent_id||""} onChange={e=>updateStep(i,"agent_id",Number(e.target.value))}><option value="">Select team member</option>{members.map(m=><option key={m.user} value={m.user}>{m.email}</option>)}</select>:null}
      {step.type==="notify_team"?<input placeholder="Notification" value={step.message||""} onChange={e=>updateStep(i,"message",e.target.value)}/>:null}
      {step.type==="delay"?<input min="0" type="number" placeholder="Seconds" value={step.seconds||0} onChange={e=>updateStep(i,"seconds",Number(e.target.value))}/>:null}
      {step.type==="branch"?<div className="automation-media-action"><small>Targets use the one-based step numbers shown in this builder.</small>{[0,1,2].map(branchIndex=>{const branch=step.branches?.[branchIndex]||{};const change=(field,value)=>{const branches=[...(step.branches||[])];branches[branchIndex]={...branch,[field]:value};updateStep(i,"branches",branches);};return <div className="automation-builder-row" key={branchIndex}><input aria-label={`Branch ${branchIndex+1} reply`} placeholder={`Reply ${branchIndex+1}`} value={branch.value||""} onChange={e=>change("value",e.target.value)}/><input aria-label={`Branch ${branchIndex+1} target step`} max={steps.length} min="1" placeholder="Go to step" type="number" value={branch.next_step||""} onChange={e=>change("next_step",Number(e.target.value))}/></div>;})}<input aria-label="Unmatched reply message" placeholder="Please reply with 1, 2, or 3." value={step.unmatched_reply||""} onChange={e=>updateStep(i,"unmatched_reply",e.target.value)}/></div>:null}
    </div>)}<button className="button" onClick={()=>setSteps(x=>[...x,emptyStep()])}>Add Step</button></article>{error?<p className="form-error">{error}</p>:null}</div></section>;
}
export default FlowBuilder;
