# Generated by Django 5.2.16 on 2026-07-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationlog',
            new_name='automations_organiz_3c4c55_idx',
            old_name='automation__organiz_7d9a91_idx',
        ),
        migrations.RenameIndex(
            model_name='automationlog',
            new_name='automations_organiz_6e959e_idx',
            old_name='automation__organiz_6cecff_idx',
        ),
        migrations.RenameIndex(
            model_name='automationrule',
            new_name='automations_organiz_7cfc18_idx',
            old_name='automation__organiz_461d1c_idx',
        ),
    ]
