import { useState } from "react";
import { X } from "lucide-react";
import { commitWhatsAppWorkbook, inspectWhatsAppSheet, previewWhatsAppWorkbook, uploadWhatsAppWorkbook } from "../../services/contactService.js";

const fields = [["whatsapp_number", "WhatsApp Number *"], ["business_name", "Business Name"], ["category", "Category"], ["email", "Email"], ["website", "Website"], ["address", "Address"], ["whatsapp_status", "WhatsApp Status"], ["evidence_type", "Evidence Type"], ["evidence_url", "Evidence URL"], ["provider", "Provider / Source"]];

export default function WhatsAppExcelImport({ categories, onClose, onImported }) {
  const [step, setStep] = useState(1), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [file, setFile] = useState(null), [book, setBook] = useState(null), [sheet, setSheet] = useState(null);
  const [mappings, setMappings] = useState({}), [defaultCategory, setDefaultCategory] = useState(""), [confirmed, setConfirmed] = useState(false), [result, setResult] = useState(null);
  const unknown = categories.find((c) => c.name === "Unknown")?.id;
  const options = { token: book?.token, sheet: sheet?.name, mappings, default_category_id: defaultCategory || unknown, confirmed };
  async function run(fn) { setBusy(true); setError(""); try { await fn(); } catch (e) { setError(e.response?.data?.detail || "The import could not be processed."); } finally { setBusy(false); } }
  function upload() { run(async () => { const value = await uploadWhatsAppWorkbook(file); setBook(value); if (value.sheet) { setSheet(value.sheet); setMappings(value.sheet.suggested_mappings || {}); } setDefaultCategory(String(unknown || "")); setStep(2); }); }
  function choose(name) { run(async () => { const value = await inspectWhatsAppSheet(book.token, name); setSheet(value); setMappings(value.suggested_mappings || {}); }); }
  function makePreview() { run(async () => { setResult(await previewWhatsAppWorkbook(options)); setStep(4); }); }
  function commit() { run(async () => { setResult(await commitWhatsAppWorkbook(options)); setStep(5); await onImported(); }); }
  const rawRows = sheet?.rows || [], mappedRows = rawRows.slice(0, 10);
  return <div className="contact-modal" role="presentation"><div className="contact-modal__scrim" onClick={onClose}/><section aria-modal="true" className="panel excel-import" role="dialog">
    <div className="contact-form__header"><div><small>Excel WhatsApp import · Step {step} of 5</small><h2>Import WhatsApp Contacts</h2></div><button aria-label="Close import" className="icon-button" onClick={onClose}><X size={16}/></button></div>
    <div className="excel-import__steps">{["Upload", "Sheet", "Columns", "Preview", "Results"].map((label, i) => <span className={step === i + 1 ? "active" : ""} key={label}>{i + 1} {label}</span>)}</div>
    {error && <p className="form-error">{error}</p>}
    {step === 1 && <div className="excel-import__body"><h3>Upload Excel Workbook</h3><p>Supported format: .xlsx, up to 8 MB. Formulas and macros are not executed.</p><input accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e) => setFile(e.target.files[0])} type="file"/>{file && <p>{file.name} · {(file.size / 1024).toFixed(1)} KB</p>}<div className="actions"><button className="button button--primary" disabled={!file || busy} onClick={upload}>{busy ? "Reading workbook..." : "Continue"}</button></div></div>}
    {step === 2 && sheet && <div className="excel-import__body"><label>Select Worksheet<select value={sheet.name} onChange={(e) => choose(e.target.value)}>{book.sheets.map((name) => <option key={name}>{name}</option>)}</select></label><p>Workbook contains {book.sheets.length} sheet{book.sheets.length === 1 ? "" : "s"}. Detected header row: {sheet.header_row}.</p><Preview headers={sheet.headers} rows={rawRows}/><div className="actions"><button className="button" onClick={() => setStep(1)}>Back</button><button className="button button--primary" onClick={() => setStep(3)}>Map Columns</button></div></div>}
    {step === 3 && sheet && <div className="excel-import__body"><div className="excel-import__mapping">{fields.map(([key, label]) => <label key={key}>{label}<select value={mappings[key] || ""} onChange={(e) => setMappings({...mappings, [key]: e.target.value})}><option value="">Not mapped</option>{sheet.headers.map((header) => <option key={header}>{header}</option>)}</select></label>)}<label>Default Category<select value={defaultCategory} onChange={(e) => setDefaultCategory(e.target.value)}>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><h3>Mapped Preview</h3><Preview headers={fields.filter(([key]) => mappings[key]).map(([,label]) => label.replace(" *", ""))} rows={mappedRows.map((row) => Object.fromEntries(fields.filter(([key]) => mappings[key]).map(([key,label]) => [label.replace(" *", ""), row[mappings[key]]])))} /><label className="checkbox-label"><input checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} type="checkbox"/>I confirm that the mapped number column contains WhatsApp contact numbers that I am authorized to store/import.</label><div className="actions"><button className="button" onClick={() => setStep(2)}>Back</button><button className="button button--primary" disabled={!mappings.whatsapp_number || !confirmed || busy} onClick={makePreview}>{busy ? "Preparing preview..." : "Preview Import"}</button></div></div>}
    {step === 4 && result && <div className="excel-import__body"><Summary data={result.summary}/><Preview headers={["Row", "Business", "WhatsApp", "Category", "Result"]} rows={result.rows.map((r) => ({Row:r.row, Business:r.business_name, WhatsApp:r.number || r.whatsapp_number, Category:r.category, Result:r.status}))}/><p>No database changes have been made.</p><div className="actions"><button className="button" onClick={() => setStep(3)}>Back</button><button className="button button--primary" disabled={busy} onClick={commit}>{busy ? "Importing WhatsApp contacts..." : `Import ${result.summary.new} WhatsApp Contacts`}</button></div></div>}
    {step === 5 && result && <div className="excel-import__body"><h3>Import complete</h3><Summary data={result.summary}/><div className="actions"><button className="button button--primary" onClick={onClose}>View Contacts</button></div></div>}
  </section></div>;
}
function Preview({headers, rows}) { return <div className="table-wrap excel-import__table"><table className="contacts-table"><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,15).map((row,i) => <tr key={row._row || i}>{headers.map((h) => <td key={h}>{row[h] || "—"}</td>)}</tr>)}</tbody></table></div>; }
function Summary({data}) { return <div className="excel-import__summary">{Object.entries(data).map(([key,value]) => <div key={key}><strong>{value}</strong><span>{key.replaceAll("_", " ")}</span></div>)}</div>; }
