import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("contacts", "0001_initial"), ("conversations", "0002_message_media_fields"), ("organizations", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="CustomerFlow", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=255)), ("description", models.TextField(blank=True)), ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active")], db_index=True, default="draft", max_length=20)), ("start_trigger_json", models.JSONField(default=dict)), ("steps_json", models.JSONField(default=list)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_flows", to="organizations.organization"))], options={"ordering": ["-updated_at"]}),
        migrations.CreateModel(name="FlowRun", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(choices=[("running", "Running"), ("waiting", "Waiting"), ("completed", "Completed"), ("failed", "Failed")], db_index=True, default="running", max_length=20)), ("current_step", models.PositiveIntegerField(default=0)), ("state_json", models.JSONField(blank=True, default=dict)), ("started_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flow_runs", to="contacts.contact")), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flow_runs", to="conversations.conversation")), ("flow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="flows.customerflow")), ("last_inbound_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="advanced_flow_runs", to="conversations.message")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flow_runs", to="organizations.organization"))], options={"ordering": ["-updated_at"]}),
        migrations.CreateModel(name="FlowLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("step_index", models.PositiveIntegerField(default=0)), ("step_type", models.CharField(max_length=40)), ("status", models.CharField(max_length=20)), ("message", models.TextField(blank=True)), ("whatsapp_message_id", models.CharField(blank=True, max_length=255)), ("created_at", models.DateTimeField(auto_now_add=True)), ("inbound_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="flow_logs", to="conversations.message")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flow_logs", to="organizations.organization")), ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="flows.flowrun"))], options={"ordering": ["created_at"]}),
        migrations.AddIndex(model_name="customerflow", index=models.Index(fields=["organization", "status"], name="flows_custo_organiz_60b292_idx")),
        migrations.AddConstraint(model_name="flowrun", constraint=models.UniqueConstraint(condition=models.Q(("status__in", ["running", "waiting"])), fields=("flow", "contact"), name="one_active_run_per_flow_contact")),
        migrations.AddConstraint(model_name="flowlog", constraint=models.UniqueConstraint(condition=models.Q(("inbound_message__isnull", False)), fields=("run", "inbound_message"), name="flow_run_inbound_once")),
    ]
