import { useEffect, useRef } from "react";
import { Building2, Check, Download, ExternalLink, Search, Upload, Users, X } from "lucide-react";
import { contactStatus, dataCoverage, providerSources } from "../utils/leadCollectorHelpers.js";

export function ResultOverview({ businesses, searchResult, categoryName, centerLabel, radiusMeters, providerNames, searchDepth }) {
  const coverage = dataCoverage(businesses); const searched = Boolean(searchResult);
  return <aside className="overview-summary panel"><div className="collector-section-heading"><div><span>Search summary</span><h2>{searched ? `${businesses.length} businesses found` : "Search setup"}</h2></div></div>
    <dl className="summary-list"><div><dt>Location</dt><dd title={centerLabel}>{centerLabel || "Not selected"}</dd></div><div><dt>Radius</dt><dd>{radiusMeters / 1000} km</dd></div><div><dt>Providers</dt><dd>{providerNames || "Not selected"}</dd></div>{searchDepth && <div><dt>Search depth</dt><dd>{searchDepth}</dd></div>}<div><dt>Category</dt><dd>{categoryName}</dd></div><div><dt>Businesses</dt><dd>{searched ? `${businesses.length} found` : "Not searched yet"}</dd></div></dl>
    <h3>Data coverage</h3>{searched ? <div className="coverage-list">{coverage.map((item) => <div key={item.field}><div><span>{item.label}</span><strong>{item.count}/{businesses.length} · {item.percentage}%</strong></div><span aria-label={`${item.label} ${item.percentage}%`} className="coverage-track"><i style={{ width: `${item.percentage}%` }}/></span></div>)}</div> : <p className="summary-placeholder">Coverage appears after business discovery.</p>}
  </aside>;
}

export function ResultsToolbar({ businesses, categoryName, selected, loading, operation, exporting, canFindPeople, onSelectAll, onClear, onEnrich, onFindPeople, onExport, onImport }) {
  return <section className="collector-results-toolbar panel"><div className="toolbar-selection"><strong>{businesses.length} {categoryName} Found</strong><label><input checked={Boolean(businesses.length) && selected.length === businesses.length} onChange={onSelectAll} type="checkbox"/>Select All</label><span>{selected.length} selected</span><button disabled={!selected.length} type="button" onClick={onClear}>Clear</button></div><div className="toolbar-actions"><button className="button" disabled={!selected.length || loading || Boolean(exporting)} onClick={onEnrich}><Check size={14}/>{operation === "enrich" ? "Enriching selected businesses..." : "Enrich Selected"}</button><button className="button" disabled={!selected.length || loading || Boolean(exporting) || !canFindPeople} onClick={onFindPeople}><Users size={14}/>{operation === "people" ? "Finding decision makers..." : "Find Decision Makers"}</button><span className="toolbar-action-group"><button className="button" disabled={!businesses.length || loading || Boolean(exporting)} onClick={() => onExport("csv")}><Download size={14}/>{exporting === "csv" ? "Preparing enriched CSV export..." : "Export CSV"}</button><button className="button" disabled={!businesses.length || loading || Boolean(exporting)} onClick={() => onExport("excel")}><Download size={14}/>{exporting === "excel" ? "Preparing enriched Excel export..." : "Export Excel"}</button></span><button className="button button--primary" disabled={!selected.length || loading || Boolean(exporting)} onClick={onImport}><Upload size={14}/>{operation === "preview" ? "Checking CRM duplicates..." : "Add WhatsApp Contacts"}</button></div></section>;
}

function SourceBadges({ business }) { const sources = providerSources(business); return sources.length ? <span className="source-badges">{sources.map((source) => <span key={source}>{source}</span>)}</span> : <span>-</span>; }

export function BusinessResultsTable({ businesses, selected, onToggle, onView }) {
  return <section className="collector-table-wrap panel"><table><thead><tr><th aria-label="Selection"/><th>#</th><th>Business</th><th>Category</th><th>Phone / Email</th><th>Website</th><th>Distance</th><th>Sources</th><th>Status</th><th>Action</th></tr></thead><tbody>{businesses.map((item, index) => <tr key={item.id}><td><input aria-label={`Select ${item.name}`} checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} type="checkbox"/></td><td>{index + 1}</td><td className="business-cell"><strong>{item.name}</strong><small>{item.address || "Address unavailable"}</small></td><td>{item.category || "-"}</td><td><strong>{item.phone || "-"}</strong><small>{item.email || "-"}</small></td><td>{item.website ? <a href={item.website} rel="noreferrer" target="_blank">Website <ExternalLink size={11}/></a> : "-"}</td><td className="distance-cell">{item.distance_km != null ? `${Number(item.distance_km).toFixed(1)} km` : "-"}</td><td><SourceBadges business={item}/></td><td><span className={`contact-status contact-status--${contactStatus(item).toLowerCase().replace(" ", "-")}`}>{contactStatus(item)}</span></td><td><button className="table-view-button" onClick={(event) => onView(item, event.currentTarget)} type="button">View</button></td></tr>)}</tbody></table></section>;
}

function DetailRows({ rows }) { return <dl className="drawer-detail-list">{rows.map(([label, value, link]) => <div key={label}><dt>{label}</dt><dd>{value ? (link ? <a href={value} rel="noreferrer" target="_blank">{value}<ExternalLink size={12}/></a> : String(value)) : "-"}</dd></div>)}</dl>; }

export function BusinessDetailsDrawer({ business, onClose, returnFocus }) {
  const drawerRef = useRef(null); const closeRef = useRef(null);
  useEffect(() => { if (!business) return undefined; closeRef.current?.focus(); const keydown = (event) => { if (event.key === "Escape") onClose(); if (event.key !== "Tab" || !drawerRef.current) return; const focusable = [...drawerRef.current.querySelectorAll('a[href],button:not([disabled])')]; if (!focusable.length) return; const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); returnFocus?.focus?.(); }; }, [business, onClose, returnFocus]);
  if (!business) return null;
  const emails = business.business_emails || []; const phones = business.business_phones || []; const people = business.decision_makers || business.manager_contacts || []; const whatsapp = (business.whatsapp_contacts || []).filter((item) => item.status === "CONFIRMED_PUBLIC"); const social = business.social_profiles || {}; const socialSources = business.social_profile_sources || {}; const pages = business.discovered_pages || {}; const enrichmentSources = business.enrichment_sources || {};
  return <div className="collector-drawer-layer"><button aria-label="Close business details" className="collector-drawer-scrim" onClick={onClose}/><aside aria-labelledby="collector-drawer-title" aria-modal="true" className="collector-drawer" ref={drawerRef} role="dialog"><header><span className="drawer-business-icon"><Building2/></span><div><small>Business details</small><h2 id="collector-drawer-title">{business.name}</h2><SourceBadges business={business}/></div><button aria-label="Close business details" onClick={onClose} ref={closeRef}><X/></button></header>
    <section><h3>Overview</h3><DetailRows rows={[["Category", business.category], ["Brand", business.brand], ["Rating / reviews", business.rating ? `${business.rating}${business.review_count != null ? ` / ${business.review_count}` : ""}` : null], ["Distance", business.distance_km != null ? `${Number(business.distance_km).toFixed(1)} km` : null]]}/></section>
    <section><h3>Contact Information</h3><DetailRows rows={[["Primary phone", business.phone], ["Primary email", business.email], ...phones.map((item, i) => [`Additional phone ${i + 1}`, item.phone || item.normalized]), ...emails.map((item, i) => [`Additional email ${i + 1}`, item.email]), ["Website", business.website, true], ["Address", business.address]]}/></section>
    <section><h3>Enrichment</h3><DetailRows rows={[["Status", business.enrichment_status], ["Sources", Object.values(enrichmentSources).filter(Boolean).join(" · ")], ["Discovered pages", Object.values(pages).filter(Boolean).join(" · ")]]}/></section>
    <section><h3>Decision Makers</h3>{people.length ? <div className="drawer-people">{people.map((person, index) => <article key={`${person.name}-${index}`}><strong>{person.name || "Public contact"}</strong><span>{person.title || person.role_group || "Role unavailable"}</span><DetailRows rows={[["LinkedIn", person.linkedin_url, true], ["Email", person.business_email || person.email], ["Phone", person.phone], ["Source", person.source_url || person.source, Boolean(person.source_url)]]}/></article>)}</div> : <p className="drawer-empty">No public decision-makers found.</p>}</section>
    <section><h3>WhatsApp</h3>{whatsapp.length ? whatsapp.map((contact, index) => <article className="whatsapp-evidence" key={`${contact.normalized}-${index}`}><strong>{contact.normalized || contact.number}</strong><span>Confirmed public</span><small>{contact.evidence_type || "Explicit public evidence"}</small>{contact.source_url && <a href={contact.source_url} rel="noreferrer" target="_blank">View evidence</a>}</article>) : <p className="drawer-empty">No confirmed public WhatsApp evidence. Ordinary phone numbers are not treated as WhatsApp.</p>}</section>
    <section><h3>Social Profiles</h3><DetailRows rows={[["LinkedIn", social.linkedin, true], ["LinkedIn source", socialSources.linkedin, true], ["Facebook", social.facebook, true], ["Facebook source", socialSources.facebook, true], ["Instagram", social.instagram, true], ["Instagram source", socialSources.instagram, true]]}/></section>
    <section><h3>Source / Provenance</h3><DetailRows rows={[["Providers", providerSources(business).join(" · ")], ["Place ID", business.place_id || business.provider_place_id || business.google_place_id || business.osm_id], ["Coordinates", business.latitude != null && business.longitude != null ? `${business.latitude}, ${business.longitude}` : null], ["Maps URL", business.maps_url || business.google_maps_url, true]]}/></section>
  </aside></div>;
}

export function EmptyResults({ searched, loading }) {
  if (loading) return <div className="collector-empty"><Search/><span><strong>Searching businesses...</strong><small>Browser Search returns as soon as its bounded plan completes.</small></span></div>;
  return <div className="collector-empty"><Building2/><span><strong>{searched ? "No businesses were found within this search area." : "Select a location and search to discover businesses."}</strong><small>{searched ? "Try a larger radius, another provider, or a deeper Browser Search." : "Results will appear here without leaving the CRM."}</small></span></div>;
}
