# Generated by Django 5.2.15 on 2026-08-06 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("contacts", "0003_alter_contact_source"),
        ("organizations", "0003_organizationinvitation"),
        ("pipelines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)), ("code", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)), ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lead_services", to="organizations.organization")),
            ], options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)), ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("source", models.CharField(choices=[("whatsapp", "WhatsApp"), ("website", "Website"), ("blog", "Blog"), ("instagram", "Instagram"), ("facebook", "Facebook"), ("linkedin", "LinkedIn"), ("qr_code", "QR Code"), ("marketing_team", "Marketing Team"), ("referral", "Referral"), ("excel_import", "Excel Import"), ("manual_entry", "Manual Entry"), ("other", "Other")], default="manual_entry", max_length=30)),
                ("status", models.CharField(choices=[("new", "New"), ("contacted", "Contacted"), ("interested", "Interested"), ("converted", "Converted"), ("lost", "Lost")], default="new", max_length=20)),
                ("next_follow_up", models.DateTimeField(blank=True, null=True)), ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_leads", to=settings.AUTH_USER_MODEL)),
                ("contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="contacts.contact")),
                ("converted_deal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_leads", to="pipelines.deal")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_leads", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="organizations.organization")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leads", to="leads.service")),
            ], options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="service", constraint=models.UniqueConstraint(fields=("organization", "name"), name="unique_service_name_per_org")),
        migrations.AddConstraint(model_name="service", constraint=models.UniqueConstraint(fields=("organization", "code"), name="unique_service_code_per_org")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["organization", "status"], name="leads_lead_organiz_1ed3c6_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["organization", "service"], name="leads_lead_organiz_e0dd7d_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["organization", "assigned_to"], name="leads_lead_organiz_015109_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["organization", "next_follow_up"], name="leads_lead_organiz_9fd1c1_idx")),
    ]
