import { useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Search } from "lucide-react";
import { isValidEmail } from "../services/emailService.js";
export default function RecipientSelector({ recipients, selected, onChange }) {
  const [query, setQuery] = useState(""); const [source, setSource] = useState("All");
  const visible = useMemo(() => recipients.filter((r) => (source === "All" || r.source === source) && `${r.name} ${r.company} ${r.email}`.toLowerCase().includes(query.toLowerCase())), [recipients, query, source]);
  const validVisible = visible.filter((r) => isValidEmail(r.email)); const validCount = recipients.filter((r) => isValidEmail(r.email)).length;
  const toggleAll = () => { const ids = validVisible.map((r) => r.id); const all = ids.every((id) => selected.includes(id)); onChange(all ? selected.filter((id) => !ids.includes(id)) : [...new Set([...selected, ...ids])]); };
  return <section className="email-card"><div className="email-card__heading"><div><h2>Recipients</h2><p>{recipients.length} contacts available · {validCount} valid · {recipients.length - validCount} unavailable/invalid</p></div><strong>{selected.length} selected</strong></div><div className="email-toolbar"><label className="email-search"><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search contacts" /></label><select aria-label="Filter by source" value={source} onChange={(e) => setSource(e.target.value)}><option>All</option><option>Lead Collection</option><option>Contacts</option></select><button className="button button--small" onClick={toggleAll} type="button">Select all visible</button><button className="button button--small" onClick={() => onChange([])} type="button">Clear</button></div><div className="recipient-list"><div className="recipient-row recipient-row--head"><span></span><span>Name</span><span>Business</span><span>Email</span><span>Source</span></div>{visible.map((r) => { const valid = isValidEmail(r.email); return <label className={`recipient-row ${valid ? "" : "recipient-row--disabled"}`} key={r.id}><input type="checkbox" checked={selected.includes(r.id)} disabled={!valid} onChange={() => onChange(selected.includes(r.id) ? selected.filter((id) => id !== r.id) : [...selected, r.id])}/><span><strong>{r.name}</strong></span><span>{r.company}</span><span className={valid ? "recipient-email--valid" : "recipient-email--invalid"}>{valid ? <CheckCircle2 size={14}/> : <AlertCircle size={14}/>} {r.email || "Missing email"}</span><span><small>{r.source}</small></span></label>; })}</div></section>;
}
